on: [push, pull_request, workflow_dispatch]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: aws-cloudformation/aws-cloudformation-resource-providers-ses
          path: ses
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - run: |
          pip install -e .
          cd ses/*configurationset
          mvn package
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
